# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-03 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='\u59d3\u540d')),
                ('sex', models.CharField(choices=[('Male', '\u7537'), ('Female', '\u5973')], default='Male', max_length=4, verbose_name='\u6027\u522b')),
                ('professional_title', models.CharField(default='\u5927\u5b66\u6559\u5e08', max_length=120, verbose_name='\u804c\u79f0')),
                ('address', models.CharField(default='', max_length=120, verbose_name='\u5730\u5740')),
                ('college', models.CharField(default='', max_length=30, verbose_name='\u6240\u5728\u5927\u5b66')),
                ('academy', models.CharField(default='', max_length=30, verbose_name='\u5b66\u9662')),
                ('institution', models.CharField(default='', max_length=30, verbose_name='\u9662\u7cfb')),
                ('post_number', models.IntegerField(default=0, verbose_name='\u90ae\u7f16\u53f7\u7801')),
                ('phone_number', models.CharField(default='', max_length=30, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('mail', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('content', models.TextField(default='\u8bf7\u8f93\u5165\u7b80\u4ecb', verbose_name='\u7b80\u4ecb')),
                ('UG_lesson', models.TextField(default='', verbose_name='\u672c\u79d1\u751f\u8bfe\u7a0b')),
                ('PG_lesson', models.TextField(default='', verbose_name='\u7814\u7a76\u751f\u8bfe\u7a0b')),
                ('research_direction', models.TextField(default='', verbose_name='\u7814\u7a76\u65b9\u5411')),
                ('research', models.TextField(default='', verbose_name='\u79d1\u7814\u5de5\u4f5c')),
                ('hold_project', models.TextField(default='', verbose_name='\u4e3b\u6301\u79d1\u7814\u9879\u76ee')),
                ('papers', models.TextField(default='', verbose_name='\u671f\u520a\u8bba\u6587')),
                ('books', models.TextField(default='', verbose_name='\u4e66\u7c4d\u8457\u4f5c')),
                ('conference_papers', models.TextField(default='', verbose_name='\u4f1a\u8bae\u8bba\u6587')),
                ('recruitment', models.TextField(default='', verbose_name='\u62db\u8058\u516c\u544a')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
