# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 15:05
from __future__ import unicode_literals

import Teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_teacher_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='teacher',
            name='height_field',
            field=models.IntegerField(default=0, verbose_name='\u9ad8\u5ea6'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=Teachers.models.upload_location, verbose_name='\u5934\u50cf', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='width_field',
            field=models.IntegerField(default=0, verbose_name='\u5bbd\u5ea6'),
        ),
    ]
