# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0003_auto_20160904_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('Male', '\u7537'), ('Female', '\u5973')], default='Male', max_length=10, verbose_name='\u6027\u522b'),
        ),
    ]
